---
title: "A brief history of how I got to where I am and where I might go someday. "
---

I am considered an **Entomologist** by most, a **Quantitative Ecologist** by some, and in a former life, I was an **Agroecologist**. I am from a small town in Northeastern Pennsylvania, where I spent much of my time wrestling, playing baseball, skateboarding, hunting, and fishing. Indeed, I was a *bug kid*, but it was not until my junior year of undergrad that I learned studying arthropods could be a career. From that moment on, I dedicated much of time to learning all I could about insects and other arthropods. I added the entomology minor to my course load which added a year to my degree, took graduate-level courses, sought internships with a focus on entomology, and started considering graduate programs. I finished my undergraduate degree with a major in Plant Sciences, Agroecology option, and minors in Entomology, International Agriculture, and Soil Science. 

  Upon the completion of my undergraduate degree in December 2019, I joined **Peace Corps Nepal**. Regrettably, due to the COVID-19 pandemic, in March of 2020, the Peace Corps underwent a global evacuation from all countries. Upon returning to the US, I got a job in agri-chemical research at [Lehigh Agricultural and Biological Services](https://www.labservices.com/). I had interned here as an undergraduate, so, the transition to a full-time employee was all but seamless. In 2021, I went back to Penn State to work for [Dr. John Wallace](https://plantscience.psu.edu/directory/jmw309) in the **Weed Science** department. While I loved working for Wallace, my passion was (and still is) **entomology**, and in 2022 I finally joined my first **Entomology lab**. In August of 2022, I started a Master's degree with [Dr. John Tooker](https://ento.psu.edu/research/labs/john-tooker).

  At present, I am a PhD student of [Dr. Will Wetzel](https://wetzellab.com/) in the Land Resources and Environmental Sciences (LRES) program in the College of Agriculture at **Montana State University**. I am broadly interested in how global environmental change drives plant-insect interactions. My work focuses on plant **tolerance** to herbivory and I seek to understand how plants can, or cannot, handle an increase in both abiotic and biotic stress. For example, how does an increase in abiotic stress drive insect-herbivore populations? What physiological traits do plants rely to *handle* an increase in the **dual threat** of abiotic and biotic pressure? Can we predict the role of arthropod predators in plant fitness?

  Upon the completion of my PhD, I would like to teach entomology and applied statistics and programming through an ecological lens. I see myself working at a small-mid sized R1 university, but am open to job opportunities that allow me to build curriculum. For more information about my teaching history and plans for the future, please see [this](teaching.qmd) page. 